### ISSUE TITLE
Image preprocessing

### ISSUE THREAD

**Issue by wangken1994** [ginobilinie/medSynthesisV1#11]
Hellow,
      I want to ask how the image is registered about 3T to 7T.

**Comment by ginobilinie** [comment]
@wangken1994 Thanks for your interest. Personally, I donot involve in the data preprocessing, but i have asked the guy who did this work, and I'll let you know if he answered me.

Thanks.

**Comment by ginobilinie** [comment]
@wangken1994 We use flirt dof=6 for registration. We use rigid registration here and donot use non-rigid registration.

**Comment by wangken1994** [comment]
Thank you ,Is the 3T image of each individual registered to the 7T image? Or register data from all training sets to a standard space such as ICBM152?    Is the input of the 2D model a slice in one direction? Such as axial。Is the input to the 3D model the .nii data for the entire brain? I am a newbie, thank you very much for answering my question.

**Comment by ginobilinie** [comment]
The 3T image of each individual is registered to the corresponding 7T image.

**Comment by wangken1994** [comment]
@ginobilinie Thank you very much.

**Comment by wangken1994** [comment]
Hellow,
      What dose dFA ，dSeg ，step mean in extract23DPatch4MultiModalImg.py？

**Comment by wangken1994** [comment]
What is the data size of MR and CT data？ 153*193*50？

**Comment by ginobilinie** [comment]
dFA is one of the input modality, dSeg is the output Modality, step size is the stride during patch extraction in a sliding window manner.
MR/CT size: 256x256x(120-320)

**Comment by wangken1994** [comment]
hellow
![image](https://user-images.githubusercontent.com/34388336/70709452-e2845c80-1d17-11ea-8dcc-6fee962c092f.png)
Why MRI is [5,64,64],ct[1,64,64]?

**Comment by wangken1994** [comment]
Both of them should be [1,64,64] 。  Did I get it wrong？

**Comment by ginobilinie** [comment]
@wangken1994 I'd like to make use 5 slices of source modality to predict the corresponding middle slice of the target slice. That's why I set 5x64x64->1x64x64. Actually, if your gpu allows, you can set up large patches, like 5x240x240->1x240x240
