### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by luciaL** [ginobilinie/medSynthesisV1#12]
Dear Dr. Nie
      Thank you for your great job.
      I'm working on medical image  synthesis too. But I am new.
      I don't how to do preprocessing for CT  values. Should I normalize it to 0-255 or just let be original  
CT value. 
      Look forward to your reply.

lucia

**Comment by ginobilinie** [comment]
I think you'd better use some global constant (I mean statistics from the training set), for example, global max, global min, global mean, to convert the CT value to [-1, 1] or [-3, 3] or [0,1]

Then, you can recover the CT value to the normal region during testing stage using these global constants. CT intensities have physical meaning.

**Comment by luciaL** [comment]
@ginobilinie 
Thank you so much.
It helps a lot.
