### ISSUE TITLE
MRI datasets synthetic CT datasets

### ISSUE THREAD

**Issue by lfxuan** [ginobilinie/medSynthesisV1#13]
Thank you very much for your excellent work. I am very interested in your work. Now there are some labeled MRI datasets. Can you help me to synthesize the corresponding labeled CT datasets? Look forward to your reply!

**Comment by ginobilinie** [comment]
@lfxuan Yes, please send your data to me. But I cannot guarantee the quality of the synthesized CT since my model is trained with a small dataset.

**Comment by lfxuan** [comment]
Hello, I have sent the data to you by email. Thank you again for your help!
