### ISSUE TITLE
run “extract23Dpatches4SingleImg.py”

### ISSUE THREAD

**Issue by 921974496** [ginobilinie/medSynthesisV1#17]
Hellow ,I encountered some difficulties
  File "F:/PycharmProjects/untitled1/extract23DPatch4SingleModalImg.py", line 183, in extractPatch4OneSubject
    trainFA[cubicCnt, 0, :, :, :] = volFA
ValueError: could not broadcast input array from shape (5,64,41) into shape (5,64,64)

**Comment by 921974496** [comment]
I have solved the above problem, I want to ask why reverse along the 1st dimension
![image](https://user-images.githubusercontent.com/49221720/77248810-68993300-6c77-11ea-9e31-dbffacad0cde.png)

**Comment by ginobilinie** [comment]
It is for data augmentation (flipping)
