### ISSUE TITLE
Using different modality Data set

### ISSUE THREAD

**Issue by SurbhiKhushu** [ginobilinie/medSynthesisV1#19]
Hello,
First of all Thank you for your work. 
I am also intrested in doing  medical image synthesis but for PET and CT, instead of MRI.
Can you tell me ,what could be possible issues I should keep in mind if I implement your code for my dataset?

**Comment by ginobilinie** [comment]
Actually, this copy of code has been applied to PET/CT synthesis. Just check if it is single-modality input or multi-modality input.

**Comment by SurbhiKhushu** [comment]
My source is PET and target is generating  CT data.  It will be single modality input, I suppose:

Can you expalin what is matFA, matSeg, matMask  in line 74: 
def extractPatch4OneSubject(matFA, matSeg, matMask, fileID, d, step, rate):
Since I have preprocessed my DICOM slices and saved it  as a volume data into a flat file .mf2 format.
I want to extract  patches of  size to 64 × 64 × 64 .
