### ISSUE TITLE
Some problems about the data loader

### ISSUE THREAD

**Issue by KingsleyBw** [ginobilinie/medSynthesisV1#2]
Hi, I'm trying to use this network to deal with 3T-to-7T. But I find there is a function in "extract23DPatchMultiModalImg.py" called extractPatch4OneSubject(matLPET, matCT, matSPET, maskimg, fileID,dSeg,step,rate). I wonder in my case, what do I need  for matLPET, matCT, matSPET, masking. Thank you!

**Comment by ginobilinie** [comment]
@KingsleyBw  I'm so sorry that I donot make it clear. matLPET is for a low-resolution modality (like 3T), matSPET is for high-resolution modality (like 7T), and matCT means a extra modality if you have (if you donot have an extra modality, you can assign 3T to this modality, you can avoid to use it when you run the runCTRecon.py. And matMask is for a mask to exclude some region if you have such stuff, if you have no such stuff, you can assign a same-size np.zeros(your_3T_data).

Hope it is helpful for you

**Comment by KingsleyBw** [comment]
Thank you!
 I have another question, in "runCTRecon.py"  I found three paths: path_test, path_patients_h5, path_patients_h5_test. I wonder what is the difference between these three? Really grateful for your help.

**Comment by ginobilinie** [comment]
path_test indicates path for .nii.gz file, path_patients_h5 is for the training h5 data, and path_patients_h5_test for the validation h5 data.

**Comment by JCFu** [comment]
Hi @ginobilinie ,
I still have questions in this issue.

What path should be set separately in row 206 and 207 of _extract23DPatch4SingleModalImg.py_?
```
path = '/home/niedong/Data4LowDosePET/data_niigz_scale/'
path = '/shenlab/lab_stor5/dongnie/brain_mr2ct/original_data/' # path to the data, change to your own path
```

I want to input _.nii.gz_ files, should I change the _'.hdr'_ in the row 208 and 230?
```
scan = ScanFile(path, postfix='_mr.hdr') # the specify item for your files, change to your own style
target_fn = filename.replace('_mr.hdr', '_ct.hdr')
```

Each _nii.gz_ file generates two _.h5_ files. What is the difference between two _.h5_ files?

Thank you!

**Comment by idhamari** [comment]
@takerujason HI, I have similar questions. Did you find out the answers to your questions? did you manage to run the code?

**Comment by ginobilinie** [comment]
@takerujason @idhamari 

Sorry for the late reply.

Yes, .nii.gz should be changed to your own data format.

one .nii.gz generates two hd5 file because I do data augmentation by flipping.

**Comment by idhamari** [comment]
@ginobilinie 

> one .nii.gz generates two hd5 file because I do data augmentation by flipping.

Thanks for your explanation. Could you please check my other issues and provide some feedback.

**Comment by ginobilinie** [comment]
path =  /path/to/your/data
