### ISSUE TITLE
lambda  parameter settings

### ISSUE THREAD

**Issue by 921974496** [ginobilinie/medSynthesisV1#23]
lambda_AD  lambda_gdl lossBase  lambda_D_WGAN_GP 
How to set these parameters？  Is it by setting these parameters that the loss is in the same order of magnitude?

**Comment by ginobilinie** [comment]
Honestly speaking, it's hard to answer. You can try several values (like what we give the the code). But I donot think we should set the loss to make them the same order of magnitude.

**Comment by 921974496** [comment]
Questions about ACM

“ The only difference is about the input to the generator, which concatenates the source MRI patch and the synthetic target patch since the 1st iteration of ACM.“

I didn't find  “concatenates the source MRI patch and the synthetic target patch” in the code

**Comment by 921974496** [comment]
I want to ask about what software is used to implement difference map ?
 
For example：
difference map between the synthetic CT and ground truth CT

**Comment by ginobilinie** [comment]
Do you mean the visualization of difference map? I use matlab and ITKSnap.

**Comment by 921974496** [comment]
> Do you mean the visualization of difference map? I use matlab and ITKSnap.

Thank you very mach ,Can you send me the MATLAB code? If it's not convenient, don't send it

**Comment by 921974496** [comment]
> Do you mean the visualization of difference map? I use matlab and ITKSnap.

And how is ACM implemented?
