### ISSUE TITLE
Patch Exctraction Doubt

### ISSUE THREAD

**Issue by SurbhiKhushu** [ginobilinie/medSynthesisV1#24]
Hello,
The patches which are extracted are 2D ptches or 3D patches. Also Since I am working on PET to CT conversion, I will be using patch extraction for Multimodality right?

**Comment by ginobilinie** [comment]
Larger 2D is suggested considering 2D network is much easier to train.

PET to CT, so your input is single modality, you should use singlemodality.

**Comment by SurbhiKhushu** [comment]
Thank you for your quick response.
I have one more doubt. I have volumetric images and would like to extract 2D patches out of it. Can you tell me where I would have to changes

**Comment by ginobilinie** [comment]
It is for 2d or 3d, so you can set the patch size to be 1*64*64 (2d) or 32*32*32 (3d).
