### ISSUE TITLE
Final output resconstructed from patches to image

### ISSUE THREAD

**Issue by SurbhiKhushu** [ginobilinie/medSynthesisV1#25]
Hello,

Can you tell me which lines of the code, reconstruct the output patches back to the entire image?
How have you implemented this.
Thank you
Best Regards

**Comment by ginobilinie** [comment]
read this python file:

https://github.com/ginobilinie/medSynthesisV1/blob/master/runTesting_Reconv2.py

**Comment by SurbhiKhushu** [comment]
How do I use the 3d version of this implementation? I have an input image with 128*128

**Comment by ginobilinie** [comment]
you cannot use it if your image is 2d.

**Comment by SurbhiKhushu** [comment]
Sorry, I have image size of 128*128*128

**Comment by ginobilinie** [comment]
https://github.com/ginobilinie/medSynthesisV1/blob/master/runTesting_Reconv2.py
