### ISSUE TITLE
the problem when test one subject

### ISSUE THREAD

**Issue by CCaoyu** [ginobilinie/medSynthesisV1#29]
Hello, What is the difference between 'sub1_sourceCT.nii.gz', 'sub1_extraCT.nii.gz', and 'sub1_targetCT.nii.gz' in runCTRecon3d.py when test one subject？

**Comment by ginobilinie** [comment]
sub1_sourceCT.nii.gz is the main input modality, and sub1_extract.nii.gz is the extra input modality, sub1_targetCT.nii.gz is the output modality.
