### ISSUE TITLE
when run ur code,I met a mistake

### ISSUE THREAD

**Issue by RicckyLiu** [ginobilinie/medSynthesisV1#7]
when run your code 'extract23DPatch4SingleModalImg.py', I met a mistake
'OSError: Unable to create file (unable to open file: name = './trainMRCT_snorm_64_IXI-T1\IXI002-Guys-0828-T1.nii.gz.h5', errno = 2, error message= 'No such file or directory', flags = 13, o_flags = 302)',
is it because of I using the wrong type of file'IXI-T1\IXI002-Guys-0828-T1.nii.gz' or something else?

**Comment by ginobilinie** [comment]
read the error: no such directory~~~

**Comment by RicckyLiu** [comment]
Thank you very much. I got it！
