### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by liuhh02** [ginobilinie/medSynthesisV1#9]
Thank you very much for the great repo! I am facing a problem when running the extract23DPatch4MultiModalImg.py file:

> Traceback (most recent call last):
File "<ipython-input-76-64f212475f29>", line 95, in extractPatch4OneSubject
matFAOut=np.zeros([row+2*marginD[0],col+2*marginD[1],leng+2*marginD[2]],dtype=np.float16)
TypeError: 'float' object cannot be interpreted as an integer

Is there any way I can fix this problem? Thank you!

**Comment by lyc-lang** [comment]
use // in ` margin1 = (dFA[0] - dSeg[0]) // 2` instead.
